/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface I4My_account {
        "buttonText": string;
        "link": string;
    }
}
declare global {
    interface HTMLI4My_accountElement extends Components.I4My_account, HTMLStencilElement {
    }
    var HTMLI4My_accountElement: {
        prototype: HTMLI4My_accountElement;
        new (): HTMLI4My_accountElement;
    };
    interface HTMLElementTagNameMap {
        "i4-my_account": HTMLI4My_accountElement;
    }
}
declare namespace LocalJSX {
    interface I4My_account {
        "buttonText"?: string;
        "link"?: string;
    }
    interface IntrinsicElements {
        "i4-my_account": I4My_account;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "i4-my_account": LocalJSX.I4My_account & JSXBase.HTMLAttributes<HTMLI4My_accountElement>;
        }
    }
}
